In [2]:
import numpy as np
import pandas as pd

In [3]:
data= pd.read_csv("Food_Security_Dataset.csv")
dataset = data.dropna(axis = 0, how ='any')

In [4]:
type(dataset)

pandas.core.frame.DataFrame

In [5]:
dataset

Year  Area Harvested (1000 Ha)  Production Quantity (1000 MT)  \
0   1991                    101579                         160567   
1   1992                    101022                         170775   
2   1993                    101683                         173973   
3   1994                    101621                         176532   
4   1995                    100897                         176854   
5   1996                    101778                         183435   
6   1997                    101802                         188763   
7   1998                    102498                         189047   
8   1999                    103750                         197813   
9   2000                    104081                         199321   
10  2001                    101850                         202976   
11  2002                     96101                         177665   
12  2003                    100279                         198327   
13  2004                     99644                         196263   
14  2005                    101421                         202581   
15  2006                    101173                         204638   
16  2007                    102955                         221482   
17  2008                    103345                         226900   
18  2009                     99404                         213325   
19  2010                    102262                         229832   
20  2011                    102824                         245139   
21  2012                     99684                         250976   
22  2013                    101501                         254786   
23  2014                    100976                         256231   

    Import Quantity (1000 MT)  Export Quantity (1000MT)  \
0                      354.82                   1357.15   
1                     3419.77                    881.73   
2                      456.87                   1156.24   
3                      259.94                   4325.88   
4                      256.87                   4770.66   
5                     2009.77                   3960.52   
6                     2485.05                   4544.10   
7                     1719.31                   2595.25   
8                     2048.17                   1993.78   
9                      262.25                   4096.11   
10                     220.89                   9369.74   
11                     193.60                   8160.14   
12                     213.62                   8187.06   
13                     212.25                   8005.56   
14                     583.21                   5692.49   
15                    6675.63                   6927.34   
16                    1823.69                   6922.58   
17                      37.24                   6064.57   
18                     207.36                   5181.68   
19                     211.70                   8062.36   
20                      13.91                  16509.40   
21                      53.39                  24759.71   
22                      49.46                  21889.38   
23                     179.31                  14986.56   

    Food Availability per capita (kg/cap/yr)  
0                                     160.27  
1                                     161.30  
2                                     162.60  
3                                     162.51  
4                                     160.49  
5                                     162.32  
6                                     161.81  
7                                     161.24  
8                                     161.41  
9                                     159.41  
10                                    162.53  
11                                    158.73  
12                                    156.45  
13                                    159.14  
14                                    157.60  
15                                    157.58  
16 

In [6]:
x= dataset.iloc[:,:1]

In [7]:
x

Year
0   1991
1   1992
2   1993
3   1994
4   1995
5   1996
6   1997
7   1998
8   1999
9   2000
10  2001
11  2002
12  2003
13  2004
14  2005
15  2006
16  2007
17  2008
18  2009
19  2010
20  2011
21  2012
22  2013
23  2014

In [8]:
type(x)

pandas.core.frame.DataFrame

In [9]:
x=x.to_numpy()

In [10]:
x

array([[1991],
       [1992],
       [1993],
       [1994],
       [1995],
       [1996],
       [1997],
       [1998],
       [1999],
       [2000],
       [2001],
       [2002],
       [2003],
       [2004],
       [2005],
       [2006],
       [2007],
       [2008],
       [2009],
       [2010],
       [2011],
       [2012],
       [2013],
       [2014]], dtype=int64)

In [11]:
x.ndim

2

In [12]:
type(x)

numpy.ndarray

In [13]:
y= dataset.iloc[:,5:]

In [14]:
y

Food Availability per capita (kg/cap/yr)
0                                     160.27
1                                     161.30
2                                     162.60
3                                     162.51
4                                     160.49
5                                     162.32
6                                     161.81
7                                     161.24
8                                     161.41
9                                     159.41
10                                    162.53
11                                    158.73
12                                    156.45
13                                    159.14
14                                    157.60
15                                    157.58
16                                    157.28
17                                    154.98
18                                    157.81
19                                    157.78
20                                    154.60
21                                    157.62
22                                    157.53
23                                    155.19

In [15]:
y=y.to_numpy()

In [16]:
y

array([[160.27],
       [161.3 ],
       [162.6 ],
       [162.51],
       [160.49],
       [162.32],
       [161.81],
       [161.24],
       [161.41],
       [159.41],
       [162.53],
       [158.73],
       [156.45],
       [159.14],
       [157.6 ],
       [157.58],
       [157.28],
       [154.98],
       [157.81],
       [157.78],
       [154.6 ],
       [157.62],
       [157.53],
       [155.19]])

In [17]:
from sklearn.model_selection import train_test_split                #previously cros_validation was used in sklearn
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

In [18]:
x_train

array([[2007],
       [1999],
       [1997],
       [2008],
       [1995],
       [1993],
       [1996],
       [2009],
       [2000],
       [1998],
       [2010],
       [1994],
       [1991],
       [2012],
       [2006],
       [2003]], dtype=int64)

In [19]:
x_test

array([[2002],
       [2001],
       [2013],
       [2005],
       [2011],
       [1992],
       [2004],
       [2014]], dtype=int64)

In [20]:
from sklearn.linear_model import ElasticNet

In [22]:
en=ElasticNet()

In [23]:
en.fit(x_train,y_train)

ElasticNet(alpha=1.0, copy_X=True, fit_intercept=True, l1_ratio=0.5,
           max_iter=1000, normalize=False, positive=False, precompute=False,
           random_state=None, selection='cyclic', tol=0.0001, warm_start=False)

In [24]:
y_predict=en.predict(x_test)

In [25]:
y_predict

array([159.22700036, 159.50757138, 156.14071919, 158.38528731,
       156.70186122, 162.03271052, 158.66585833, 155.86014817])

In [26]:
y_test

array([[158.73],
       [162.53],
       [157.53],
       [157.6 ],
       [154.6 ],
       [161.3 ],
       [159.14],
       [155.19]])

In [27]:
with open('Food_Security_Dataset_Predictions.csv','a') as f:
    f.write("\nFood Availability per capita")
    f.write("\n")
    f.close()
with open('Food_Security_Dataset_Predictions.csv','ab') as f:
    for i in range(2015,2026):
        ypred=en.predict(np.array([[i]]))
        ypred
        np.savetxt(f, ypred, delimiter=",", fmt='%.4f')